/**
 * DATOS DE PRUEBA de Composición — para validar la idea antes de conectar
 * Supabase. Letras originales escritas para este mock (nada con derechos).
 * Las referencias citan títulos y autores públicos con una nota de QUÉ se
 * toma de cada una; no reproducen letras ajenas.
 */
import type { ChatTurn, NotebookEntry, Reference, Song } from "./types";

const day = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const MOCK_SONGS: Song[] = [
  {
    id: "s-lluvia",
    title: "Lluvia en la ventana",
    stage: "armonia",
    key: { tonic: 9, mode: "minor" }, // La menor
    tempo: 72,
    meter: "4/4",
    mood: ["íntima", "nostálgica", "de madrugada"],
    seed: "Lo que no dijimos se quedó pegado al vidrio como la lluvia.",
    createdAt: day(18),
    updatedAt: day(0),
    refIds: ["r-hallelujah", "r-machado", "r-lluvia-amb", "r-prog-menor"],
    versions: [
      { id: "v1", at: day(18), note: "Semilla: la frase del vidrio", scope: "letra" },
      { id: "v2", at: day(12), note: "Verso 1 y coro en borrador", scope: "letra" },
      { id: "v3", at: day(6), note: "Tonalidad fijada en La menor (cantable en mi registro)", scope: "tonalidad" },
      { id: "v4", at: day(2), note: "Coro: i–VI–III–VII; el puente pide un V mayor", scope: "armonía" },
      { id: "v5", at: day(0), note: "Se reordenó: el pre-coro va antes del segundo coro", scope: "estructura" },
    ],
    sections: [
      {
        id: "sec-1",
        kind: "verso",
        label: "Verso 1",
        bars: 8,
        intent: "Escena concreta: la cocina, la madrugada, el vidrio.",
        chords: ["Am", "F", "C", "G"],
        lyrics: [
          "[Am]Son las tres y la cocina [F]sigue encendida,",
          "[C]el café se enfrió mirando la ave[G]nida.",
          "[Am]Hay un nombre que no digo en voz [F]alta,",
          "[C]hay un hueco en la silla que me [G]falta.",
        ].join("\n"),
      },
      {
        id: "sec-2",
        kind: "pre",
        label: "Pre-coro",
        bars: 4,
        intent: "Subir: de la escena al sentimiento.",
        chords: ["Dm", "E"],
        lyrics: ["[Dm]Y afuera el cielo se cae de a [E]poco,", "[Dm]y yo aquí adentro me vuelvo [E]loco."].join("\n"),
      },
      {
        id: "sec-3",
        kind: "coro",
        label: "Coro",
        bars: 8,
        intent: "La idea en una frase: lo no dicho se quedó en el vidrio.",
        chords: ["Am", "F", "C", "G"],
        lyrics: [
          "[Am]Lluvia en la ven[F]tana,",
          "[C]lo que no dijimos se quedó pe[G]gado,",
          "[Am]como gotas que no [F]bajan,",
          "[C]como un adiós que nunca fue can[G]tado.",
        ].join("\n"),
      },
      {
        id: "sec-4",
        kind: "verso",
        label: "Verso 2",
        bars: 8,
        intent: "Segunda escena: la calle, el día siguiente.",
        chords: ["Am", "F", "C", "G"],
        lyrics: ["[Am]Amanece y la ciudad no se en[F]tera,", "[C]los buses pasan como si nada [G]fuera.", "", ""].join("\n"),
      },
      {
        id: "sec-5",
        kind: "puente",
        label: "Puente",
        bars: 4,
        intent: "Cambiar el ángulo: ¿y si lo digo ahora?",
        chords: ["F", "G", "E"],
        lyrics: "",
      },
      { id: "sec-6", kind: "coro", label: "Coro final", bars: 8, chords: ["Am", "F", "C", "G"], lyrics: "" },
    ],
  },
  {
    id: "s-cafe",
    title: "Café de las seis",
    stage: "letra",
    key: { tonic: 7, mode: "major" }, // Sol mayor
    tempo: 104,
    meter: "4/4",
    mood: ["luminosa", "cotidiana", "folk"],
    seed: "Las mañanas con ella son un ritual pequeño que no quiero perder.",
    createdAt: day(9),
    updatedAt: day(1),
    refIds: ["r-folk-prog", "r-neruda"],
    versions: [
      { id: "v1", at: day(9), note: "Título y semilla desde el cuaderno", scope: "letra" },
      { id: "v2", at: day(1), note: "Verso 1 casi cerrado; el coro aún no dice nada nuevo", scope: "letra" },
    ],
    sections: [
      {
        id: "sec-c1",
        kind: "verso",
        label: "Verso 1",
        bars: 8,
        chords: ["G", "C", "G", "D"],
        intent: "La rutina como algo sagrado.",
        lyrics: [
          "[G]Seis en punto y el agua ya [C]hierve,",
          "[G]tú bostezas y el sol se atre[D]ve,",
          "[G]dos tazas, un pan y la ra[C]dio,",
          "[G]y el mundo puede esperar un [D]rato.",
        ].join("\n"),
      },
      {
        id: "sec-c2",
        kind: "coro",
        label: "Coro",
        bars: 8,
        chords: ["C", "D", "G", "Em"],
        intent: "Decir 'quédate' sin decir quédate.",
        lyrics: ["[C]Café de las [D]seis,", "[G]no me lo quites nun[Em]ca,", "", ""].join("\n"),
      },
    ],
  },
  {
    id: "s-marea",
    title: "Marea",
    stage: "idea",
    key: { tonic: 2, mode: "major" }, // Re mayor
    tempo: 88,
    meter: "6/8",
    mood: ["abierta", "mar"],
    seed: "Volver al pueblo de mi papá y encontrar que el mar sigue igual y yo no.",
    createdAt: day(3),
    updatedAt: day(3),
    refIds: ["r-lluvia-amb"],
    versions: [{ id: "v1", at: day(3), note: "Tarareo del cuaderno → canción", scope: "letra" }],
    sections: [
      { id: "sec-m1", kind: "verso", label: "Verso 1", bars: 8, chords: ["D", "G", "Bm", "A"], lyrics: "" },
      { id: "sec-m2", kind: "coro", label: "Coro", bars: 8, chords: ["G", "A", "D", "Bm"], lyrics: "" },
    ],
  },
  {
    id: "s-faro",
    title: "El faro apagado",
    stage: "demo",
    key: { tonic: 4, mode: "minor" }, // Mi menor
    tempo: 66,
    meter: "3/4",
    mood: ["vals", "oscura"],
    seed: "Un vals para alguien que dejó de ser guía.",
    createdAt: day(40),
    updatedAt: day(8),
    refIds: [],
    versions: [
      { id: "v1", at: day(40), note: "Letra completa en una tarde", scope: "letra" },
      { id: "v2", at: day(20), note: "Armonía: Em–C–G–B7 en todo", scope: "armonía" },
      { id: "v3", at: day(8), note: "Demo en el celular, voz y guitarra", scope: "estructura" },
    ],
    sections: [
      {
        id: "sec-f1",
        kind: "verso",
        label: "Verso 1",
        bars: 8,
        chords: ["Em", "C", "G", "B7"],
        lyrics: ["[Em]El faro que cuidaba la ba[C]hía", "[G]se cansó de alumbrar al que se [B7]iba."].join("\n"),
      },
      {
        id: "sec-f2",
        kind: "coro",
        label: "Coro",
        bars: 8,
        chords: ["C", "G", "B7", "Em"],
        lyrics: ["[C]Y ya no hay [G]luz,", "[B7]y ya no hay [Em]nadie."].join("\n"),
      },
    ],
  },
];

export const MOCK_REFS: Reference[] = [
  {
    id: "r-hallelujah",
    kind: "cancion",
    title: "Hallelujah",
    by: "Leonard Cohen",
    source: "youtube",
    url: "https://www.youtube.com/results?search_query=leonard+cohen+hallelujah",
    takeaway: "La letra NARRA la armonía (\"the fourth, the fifth\") — el acorde y la palabra van juntos. Probar un verso que nombre lo que pasa en la música.",
    key: { tonic: 0, mode: "major" },
    tempo: 56,
    progression: ["C", "Am", "C", "Am", "F", "G", "C", "G"],
    tags: ["balada", "6/8", "letra-armonía"],
    plan: "aplicado",
    savedAt: day(15),
  },
  {
    id: "r-machado",
    kind: "poema",
    title: "Caminante, no hay camino",
    by: "Antonio Machado",
    source: "web",
    url: "https://es.wikisource.org/wiki/Proverbios_y_cantares_(Campos_de_Castilla)",
    takeaway: "Versos de 8 sílabas con rima asonante: se cantan solos. La repetición como estribillo natural.",
    tags: ["octosílabo", "asonante", "dominio público"],
    plan: "probar",
    savedAt: day(10),
    excerpt: "Octosílabos en romance — la métrica del cantar popular en español.",
  },
  {
    id: "r-lluvia-amb",
    kind: "ambiente",
    title: "Lluvia sobre vidrio, 3 a.m.",
    by: "grabación propia",
    source: "archivo",
    takeaway: "El ritmo irregular de las gotas marca ~72 bpm sin querer. Sirve de cama para el intro.",
    tempo: 72,
    tags: ["field recording", "intro"],
    plan: "aplicado",
    savedAt: day(17),
  },
  {
    id: "r-prog-menor",
    kind: "progresion",
    title: "i–VI–III–VII (menor con luz)",
    source: "nota",
    takeaway: "En La menor: Am–F–C–G. La misma progresión del pop mayor vista desde el vi: melancolía con impulso.",
    key: { tonic: 9, mode: "minor" },
    progression: ["Am", "F", "C", "G"],
    tags: ["menor", "pop"],
    plan: "aplicado",
    savedAt: day(6),
  },
  {
    id: "r-folk-prog",
    kind: "progresion",
    title: "I–IV–I–V con bajo caminante",
    source: "nota",
    takeaway: "Tres acordes y un bajo que sube por la escala entre ellos (G–A–B–C). El movimiento está en el bajo, no en los acordes.",
    key: { tonic: 7, mode: "major" },
    progression: ["G", "C", "G", "D"],
    tags: ["folk", "guitarra"],
    plan: "probar",
    savedAt: day(8),
  },
  {
    id: "r-neruda",
    kind: "letra",
    title: "Oda a las cosas — la idea de cantarle a lo cotidiano",
    by: "Pablo Neruda (Odas elementales)",
    source: "web",
    takeaway: "Elevar un objeto común (la taza, el pan) a protagonista. 'Café de las seis' va por ahí: la rutina como ritual.",
    tags: ["cotidiano", "objeto"],
    plan: "probar",
    savedAt: day(5),
  },
  {
    id: "r-bolero",
    kind: "cancion",
    title: "Bolero clásico: la cadencia ii–V–I",
    by: "varios (Los Panchos)",
    source: "spotify",
    url: "https://open.spotify.com/search/los%20panchos",
    takeaway: "El ii–V–I al final de cada frase es lo que hace que suene 'de antes'. Guardado para una canción que todavía no existe.",
    progression: ["Dm7", "G7", "Cmaj7"],
    tags: ["bolero", "jazz", "cadencia"],
    plan: "observar",
    savedAt: day(20),
  },
  {
    id: "r-hook",
    kind: "nota",
    title: "Regla del coro: una imagen, no una explicación",
    source: "nota",
    takeaway: "Si el coro explica, la canción muere. 'Lluvia en la ventana' es una imagen; 'no supimos hablar' es una explicación.",
    tags: ["craft", "coro"],
    plan: "aplicado",
    savedAt: day(12),
  },
];

export const MOCK_NOTEBOOK: NotebookEntry[] = [
  {
    id: "n1",
    kind: "frase",
    text: "Los buses pasan como si nada fuera.",
    at: day(0),
  },
  {
    id: "n2",
    kind: "tarareo",
    text: "Melodía para el coro de Marea (en el carro)",
    at: day(1),
    audio: { seconds: 23, peaks: [0.1, 0.3, 0.5, 0.8, 0.6, 0.4, 0.7, 0.9, 0.5, 0.3, 0.6, 0.8, 0.4, 0.2, 0.5, 0.7, 0.3, 0.1] },
    songId: "s-marea",
  },
  { id: "n3", kind: "titulo", text: "Lo que el mar no devuelve", at: day(2) },
  { id: "n4", kind: "verso", text: "hay un hueco en la silla que me falta", at: day(4), songId: "s-lluvia" },
  { id: "n5", kind: "imagen", text: "La luz naranja del microondas a las 3 a.m. — única luz de la casa.", at: day(5) },
  {
    id: "n6",
    kind: "tarareo",
    text: "Idea de bajo caminante para Café",
    at: day(7),
    audio: { seconds: 41, peaks: [0.4, 0.6, 0.5, 0.7, 0.8, 0.6, 0.5, 0.4, 0.6, 0.7, 0.9, 0.7, 0.5, 0.6, 0.4, 0.3, 0.5, 0.4] },
    songId: "s-cafe",
  },
  { id: "n7", kind: "frase", text: "Quedarse es también una forma de irse.", at: day(9) },
];

/** Banco de palabras para el buscador de rimas (mock chico; en producción, un diccionario). */
export const RHYME_BANK = [
  "ventana", "mañana", "semana", "lejana", "campana", "hermana", "temprana", "sana", "gana", "lana",
  "pegado", "callado", "olvidado", "cansado", "mojado", "lado", "pasado", "cerrado", "helado", "guardado",
  "bajan", "trabajan", "rebajan", "viajan", "encajan", "atajan",
  "cantado", "nombrado", "soñado", "tocado", "llorado",
  "encendida", "avenida", "herida", "vida", "salida", "despedida", "perdida", "medida", "querida",
  "alta", "falta", "salta", "esmalta", "asalta",
  "poco", "loco", "toco", "foco", "roco", "evoco",
  "hierve", "atreve", "mueve", "llueve", "nueve", "breve", "leve", "nieve",
  "radio", "rato", "trato", "retrato", "zapato", "barato",
  "seis", "veis", "sabéis", "reyes", "leyes",
  "nunca", "trunca", "yunca",
  "entera", "fuera", "espera", "primavera", "afuera", "quisiera", "carretera", "cualquiera", "manera",
  "bahía", "día", "mía", "sabía", "quería", "todavía", "melodía", "compañía", "iba", "arriba", "deriva",
  "luz", "cruz", "nadie", "aire", "baile",
  "vidrio", "silencio", "tiempo", "viento", "cuento", "lento", "momento", "intento", "aliento",
  "mar", "hogar", "lugar", "volar", "quedar", "mirar", "cantar", "pasar",
];

export const MOCK_CHAT: Record<string, ChatTurn[]> = {
  "s-lluvia": [
    {
      id: "c1",
      role: "tú",
      at: day(0),
      text: "El verso 2 se me quedó en dos líneas. Quiero seguir con la ciudad que no se entera.",
    },
    {
      id: "c2",
      role: "hermes",
      at: day(0),
      text: "Tu verso 1 funciona porque es una escena concreta (cocina, café, silla). El verso 2 arrancó igual de bien con los buses. Te dejo tres caminos, no versos terminados — la voz es tuya:",
      suggestions: [
        {
          id: "sg1",
          kind: "verso",
          sectionId: "sec-4",
          title: "Camino A · un detalle más de la calle",
          body: "Sigue en la avenida: algo que TÚ ves y nadie más (un semáforo, un perro, una panadería abriendo). La rima de 'entera/fuera' pide terminación en -era: espera · afuera · manera · cualquiera.",
          why: "Mantiene el esquema AABB del verso 1 y el punto de vista desde la ventana.",
          options: ["…y en la esquina la panadera espera", "…y yo cuento los carros desde afuera"],
        },
        {
          id: "sg2",
          kind: "verso",
          sectionId: "sec-4",
          title: "Camino B · volver al cuerpo",
          body: "Después de la ciudad, vuelve adentro: las manos, el frío, la taza. Contraste afuera/adentro como en el pre-coro.",
          why: "El pre-coro ya juega afuera/adentro; adelantarlo aquí lo hace inevitable.",
        },
        {
          id: "sg3",
          kind: "pregunta",
          title: "Una pregunta antes de escribir",
          body: "¿Qué hora es en el verso 2? Si sigue siendo la misma noche, la canción no avanza. Si ya amaneció, ¿qué cambió en ti entre las tres y las seis?",
          why: "Las mejores segundas estrofas mueven el tiempo o el lugar. La tuya ya movió el tiempo — úsalo.",
        },
      ],
    },
    {
      id: "c3",
      role: "tú",
      at: day(0),
      text: "¿Y el puente? Está vacío y no sé qué acorde pide.",
    },
    {
      id: "c4",
      role: "hermes",
      at: day(0),
      text: "Armónicamente el puente pide salir del bucle Am–F–C–G. Dos opciones que ya están en tu tonalidad y una prestada:",
      suggestions: [
        {
          id: "sg4",
          kind: "acorde",
          sectionId: "sec-5",
          title: "F – G – E (V mayor)",
          body: "El Mi mayor (V de La menor armónica) es tensión pura: obliga a volver a Am en el coro final. Ya lo usaste en el pre-coro, así que suena 'de la familia'.",
          why: "Un puente que termina en el V hace que el último coro se sienta como llegada.",
          options: ["F", "G", "E"],
        },
        {
          id: "sg5",
          kind: "acorde",
          sectionId: "sec-5",
          title: "Dm – Am – E – Am (íntimo)",
          body: "Baja la energía en vez de subirla: iv–i–V–i. Para decir en voz baja lo que el coro grita.",
          why: "Contraste dinámico: el coro final pega más si el puente susurra.",
          options: ["Dm", "Am", "E", "Am"],
        },
        {
          id: "sg6",
          kind: "referencia",
          title: "Referencia: 'Hallelujah' (ya guardada)",
          body: "Su puente-verso usa la misma idea: el V mayor como pregunta que el coro responde.",
          why: "La tienes en el tablero con el plan 'aplicado'.",
        },
      ],
    },
  ],
  "s-cafe": [
    {
      id: "c1",
      role: "hermes",
      at: day(1),
      text: "Leí 'Café de las seis'. El verso 1 tiene objetos (agua, tazas, pan, radio) — eso es Neruda haciendo lo suyo. El coro dice 'no me lo quites nunca' y eso es una explicación, no una imagen (tu propia regla del tablero). ¿Qué VES cuando piensas en perder ese café?",
    },
  ],
};

/** Ritual del día: lo que un compositor puede hacer en 15 minutos aunque no haya inspiración. */
export const DAILY_RITUAL = [
  { id: "d1", label: "Escritura libre 10 min", hint: "Sin borrar, sin rimar. Solo llenar la página.", done: true },
  { id: "d2", label: "Un verso al cuaderno", hint: "Una línea que oíste o viste hoy.", done: true },
  { id: "d3", label: "Tocar la progresión de la canción activa", hint: "Cantarle encima aunque no haya letra.", done: false },
  { id: "d4", label: "Escuchar una referencia con lápiz", hint: "Anotar UNA cosa que tomo.", done: false },
];

/** Días con escritura en las últimas 8 semanas (mock: 1 = escribió). */
export const WRITING_DAYS: number[] = [
  0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
];
